#ifndef GIVM_DEFINITION_SUBSCRIBED_EVENTS_HPP
#define GIVM_DEFINITION_SUBSCRIBED_EVENTS_HPP

#include "../table.hpp"
#include "../utils/type_list.hpp"

namespace givm
{
    template<class EntityView>
    struct subscribed_events;

    template<>
    struct subscribed_events<hand_card_status_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct calculating_card_payment,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct hand_card_created,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed
    >{};

    template<>
    struct subscribed_events<hand_card_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct calculating_card_payment,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct hand_card_created,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct card_effect,
        struct hand_card_discard_effect
    >{};

    template<>
    struct subscribed_events<deck_card_view> : type_list<
        struct deck_card_discard_effect,
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed
    >{};

    template<>
    struct subscribed_events<deck_card_status_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed
    >{};

    template<>
    struct subscribed_events<support_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct calculating_card_payment,
        struct calculating_skill_payment,
        struct calculating_switch_payment,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_created,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_defeated,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct support_state_changed
    >{};

    template<>
    struct subscribed_events<summon_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct calculating_card_payment,
        struct calculating_skill_payment,
        struct calculating_switch_payment,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_created,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_defeated,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct resummoning,
        struct summon_state_changed
    >{};

    template<>
    struct subscribed_events<combat_status_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct calculating_card_payment,
        struct calculating_skill_payment,
        struct calculating_switch_payment,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_created,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_defeated,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct combat_status_regeneration,
        struct combat_status_state_changed
    >{};

    template<>
    struct subscribed_events<character_view> : type_list<>{};

    template<>
    struct subscribed_events<skill_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct calculating_card_payment,
        struct calculating_skill_payment,
        struct calculating_switch_payment,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_created,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_defeated,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct skill_effect
    >{};

    template<>
    struct subscribed_events<attachment_view> : type_list<
        struct test_event,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct calculating_card_payment,
        struct calculating_skill_payment,
        struct calculating_switch_payment,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_created,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_defeated,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct attachment_reapplication,
        struct attachment_state_changed,
        struct technique_effect,
        struct prepared_skill_effect
    >{};
}

#endif
