#ifndef GIVM_DEFINITION_SUBSCRIBED_EVENTS_HPP
#define GIVM_DEFINITION_SUBSCRIBED_EVENTS_HPP

#include "../table.hpp"
#include "../utils/type_list.hpp"

namespace givm
{
    template<class EntityView>
    struct subscribed_events;

    template<>
    struct subscribed_events<history_summary_definition> : type_list<
        struct history_summary_initialization,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct secret_points_changed,
        struct energy_changed,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_completed,
        struct card_played,
        struct active_character_changed,
        struct skill_used,
        struct technique_used,
        struct after_damage,
        struct healed,
        struct after_elemental_reaction,
        struct character_revived,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed
    >{};

    template<>
    struct subscribed_events<hand_card_status_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed
    >{};

    template<>
    struct subscribed_events<hand_card_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct this_card_play,
        struct this_hand_card_discard
    >{};

    template<>
    struct subscribed_events<deck_card_view> : type_list<
        struct this_deck_card_discard,
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed
    >{};

    template<>
    struct subscribed_events<deck_card_status_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_played,
        struct active_character_changed,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed
    >{};

    template<>
    struct subscribed_events<support_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_revived,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct this_support_remove,
        struct this_support_state_change
    >{};

    template<>
    struct subscribed_events<summon_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_revived,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct this_summon_remove,
        struct this_summon_resummon
    >{};

    template<>
    struct subscribed_events<combat_status_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_revived,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct this_combat_status_remove,
        struct this_combat_status_regenerate,
        struct this_combat_status_state_change
    >{};

    template<>
    struct subscribed_events<reaction_view> : type_list<
        struct damage_calculation,
        struct elemental_reaction_will_occur
    >{};

    template<>
    struct subscribed_events<character_view> : type_list<>{};

    template<>
    struct subscribed_events<skill_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_revived,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct this_skill_use
    >{};

    template<>
    struct subscribed_events<attachment_view> : type_list<
        struct action_phase_started,
        struct battle_started,
        struct round_started,
        struct before_action,
        struct round_end_declared,
        struct round_ended,
        struct dice_roll_preparation,
        struct dice_added,
        struct dice_removed,
        struct dice_converted,
        struct changing_secret_points,
        struct secret_points_changed,
        struct changing_energy,
        struct energy_changed,
        struct cost_of_card,
        struct cost_of_skill,
        struct cost_of_technique,
        struct cost_of_switch,
        struct hand_card_added,
        struct card_drawn,
        struct hand_card_discarded,
        struct deck_card_discarded,
        struct card_candidate_chosen,
        struct elemental_tuning_modification,
        struct elemental_tuning_completed,
        struct card_will_be_played,
        struct card_played,
        struct active_character_changed,
        struct skill_will_be_used,
        struct skill_used,
        struct technique_will_be_used,
        struct technique_used,
        struct damage_preparation,
        struct damage_calculation,
        struct damage_effect,
        struct after_damage,
        struct healing,
        struct healed,
        struct elemental_reaction_will_occur,
        struct after_elemental_reaction,
        struct character_will_be_defeated,
        struct character_revived,
        struct support_removed,
        struct summon_removed,
        struct combat_status_removed,
        struct attachment_removed,
        struct this_attachment_remove,
        struct this_attachment_reapply,
        struct this_attachment_state_change,
        struct this_technique_use,
        struct this_prepared_skill_use
    >{};
}

#endif
